[build]
command = """
    pip install -r requirements.txt
    mise install --all
    npm install
    npm run build
    """
publish = "."

[build.environment]


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
framework = "streamlit"
targetPort = 5000
