[build]
command = """
    pip install -r requirements.txt
    mise install python@3.11
    """
publish = "."

[build.environment]
PYTHON_VERSION = "3.11.11"

[dev]
framework = "streamlit"
targetPort = 5000
